[common]
# Language: Auto, en_US=English, ja_JP=Japanese, ru_RU=Russian
Language=ru_RU
# Window title
WindowTitle=QtScrcpy
# File save path on Android device (must end with /)
PushFilePath=/sdcard/
# Max FPS (Android 10+ only)
MaxFps=0
# Render expired video frames (skipping expired frames means lower latency)
RenderExpiredFrames=0
# Video decoding mode: -1 auto, 0 software, 1 DirectX, 2 OpenGL
UseDesktopOpenGL=-1
# Path to push scrcpy-server on Android device
ServerPath=/data/local/tmp/scrcpy-server.jar
# Custom adb path, e.g. D:/android/tools/adb.exe
AdbPath=
# Codec options, "" means default
# e.g. CodecOptions="profile=1,level=2"
# More codec options: https://d.android.com/reference/android/media/MediaFormat
CodecOptions=""
# Encoder name (must be H.264 encoder), "" means default
# e.g. CodecName="OMX.qcom.video.encoder.avc"
CodecName=""

# Set the log level (verbose, debug, info, warn, error)
LogLevel=verbose
